set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'

call vundle#end()            " required
filetype plugin indent on    " required

syntax on

set clipboard=unnamedplus
set tabstop=4
set shiftwidth=4
set expandtab
set number
set cursorbind
set scrollbind
set cursorline
set guifont=Inconsolata\ 14

